language: python

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"
  - "3.4"

install:
  - travis_retry pip install --upgrade pip pytest wallpaper

# run some tests
script:
  - py.test

after_success:
  - echo "Success!"
